
server:
  port: 8081
  servlet:
    context-path: /programacao-para-internet

spring:
  application:
    name: ppi
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Clientes
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true


